version: "3"
 
services:
  mysql:
    image: mysql:5.6
    hostname: 'mysql'
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # ローカルのmy.cnfをマウント
      - ./dmp:/docker-entrypoint-initdb.d # dmpファイルをimport
    platform: linux/x86_64

  node:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./source:/var/www/html/source # ファイルの同期永続化