version: "3"

services:
  mysql:
    image: mysql:8.0.32
    hostname: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BookBase
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf # ローカルのmy.cnfをマウント
    platform: linux/x86_64

  web-app:
    build:
      context: "./web-app"
      dockerfile: Dockerfile
    hostname: "web-app"
    ports:
      - "3000:80"
      - "24678:24678"
    volumes:
      - ./../src:/var/www/html/src # ファイルの同期永続化
    working_dir: /var/www/html/src
